config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    patch 'users/:id', to: 'registrations#update_email', as: 'user'
  end

  root to: "questions#index"

  concern :votable do
    post :vote, on: :member
  end
  concern :commentable do
    post :comment, on: :member
  end

  resources :questions, only: %i[index show new create update destroy], concerns: [:votable, :commentable] do
    resources :attachments, shallow: true, only: :destroy
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, only: %i[show create update destroy], concerns: [:votable, :commentable] do
      patch :best
    end
  end
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end

  resource :search, only: :show

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation

  def subscription(user)
    subscriptions.where(user: user).first
  end

  def subscribe!(user)
    subscriptions.create(user: user) unless subscription(user)
  end

  def unsubscribe!(user)
    subscription(user)&.destroy!
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      render json: @question, status: :created
    else
      head :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    head :no_content
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  
  before_action :find_question, only: %i[show update destroy]

  after_action :publish_question, only: :create

  include Voted
  include Commented

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
    @answer.links.build
  end

  def new
    @question = Question.new
    @question.links.build
    @question.build_reward
  end

  def create
    @question = Question.new(question_params.merge(user: current_user))
    if @question.save
      @question.subscribe!(@question.user)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted.'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:id, :name, :url, :_destroy], reward_attributes: [:name, :image])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
    if @question
      gon.question_id = @question.id
      gon.question_user_id = @question.user_id
    end
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast 'questions', ApplicationController.render(
      partial: 'questions/question',
      locals: { question: @question }
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, remote: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  #links
    = f.fields_for :links do |link|
      = render 'link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links
  p Reward:
  #reward
    = f.fields_for :reward do |r|
      p
        = r.label :name, 'Reward name'
        = r.text_field :name
      p
        = r.label :image, 'Reward image'
        = r.file_field :image, direct_upload: true
  p= f.submit submit_text

app/views/questions/_question.html.slim
p= link_to question.title, question_path(question)

app/views/questions/_question_full.html.slim
- cache [current_user&.author_of?(question), question] do
  h1= question.title
  p= question.body
  - if question.files.attached?
    = render partial: 'attachments/attachment', collection: question.files
  - if question.links.any?
    .links-list
      p Links:
      ul
        = render question.links
  - if question.reward
    p Reward:
    p= question.reward.name
    p= image_tag url_for(question.reward.image)
.subscribe
  -if can?(:create, Subscription) && !question.subscription(current_user)
    p= link_to 'Subscribe', question_subscriptions_path(question), method: :post
  -if can? :destroy, question.subscription(current_user)
    p= link_to 'Unsubscribe', subscription_path(question.subscription(current_user)), method: :delete
= render 'votes', resource: question
= render 'comments', resource: question
- if current_user&.author_of?(question)
- if can? :update, question
  p= link_to 'Edit question', '#', class: 'edit-question-link'
- if can? :destroy, question
  p= link_to 'Delete question', question_path(question), method: :delete
- if can? :update, question
  .question-form.hidden
    = render partial: 'form', locals: { submit_text: 'Save question' }

app/views/questions/index.html.slim
h1 Questions
.questions
  = render @questions
- if can? :create, Question
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'errors', resource: @question

= render partial: 'form', locals: { submit_text: 'Ask' }

app/views/questions/show.html.slim
.question-errors
  = render 'errors', resource: @question
.question
  = render 'question_full', question: @question

.answer-errors
  = render 'errors', resource: @answer
.answers
  = render @question.answers.best_first

- if can? :create, Answer
  .new-answer-form
    = render partial: 'answers/form', locals: { model: [@question, @answer], submit_text: 'Post answer' }

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('.question').html('<%= j render 'question_full', question: @question %>');
<% end %>