config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    patch 'users/:id', to: 'registrations#update_email', as: 'user'
  end

  root to: "questions#index"

  concern :votable do
    post :vote, on: :member
  end
  concern :commentable do
    post :comment, on: :member
  end

  resources :questions, only: %i[index show new create update destroy], concerns: [:votable, :commentable] do
    resources :attachments, shallow: true, only: :destroy
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, only: %i[show create update destroy], concerns: [:votable, :commentable] do
      patch :best
    end
  end
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end

  resource :search, only: :show

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :user
  belongs_to :question
  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true
  validates :best, inclusion: [true, false]

  scope :best_first, -> { order(best: :desc) }
  scope :best, -> { where(best: true) }

  after_create :new_answer_notification

  def best!
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
      question.reward.update!(user: user) if question.reward
    end
  end

  private

  def new_answer_notification
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_answer, only: %i[show update destroy best]
  before_action :find_question, only: %i[create update best]

  after_action :publish_answer, only: :create

  include Voted
  include Commented

  authorize_resource

  def show
    redirect_to @answer.question
  end

  def create
    @answer = @question.answers.build(answer_params.merge(user: current_user))
    flash.now[:notice] = 'Your answer successfully created.' if @answer.save
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
    flash.now[:notice] = 'Your answer successfully deleted.'
  end

  def best
    authorize! :best, @answer
    @answer.best!
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:answer_id] || params[:id])
  end

  def find_question
    @question = params[:question_id] ? Question.find(params[:question_id]) : @answer.question
  end

  def publish_answer
    return if @answer.errors.any?
    partial = ApplicationController.render(
        partial: 'answers/answer',
        locals: { answer: @answer, action_cable: true }
      )
    ActionCable.server.broadcast "questions/#{@question.id}/answers", {
      partial: partial,
      answer_user_id: @answer.user_id
    }
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    @answers = Question.find(params[:question_id]).answers
    render json: @answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer
  end

  def create
    @answer = current_user.answers.new(answer_params.merge(question_id: params[:question_id]))
    if @answer.save
      render json: @answer, status: :created
    else
      head :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    head :no_content
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- action_cable ||= false
- if answer.persisted?
  div id="answer-#{answer.id}"
    - cache [action_cable || current_user&.author_of?(answer), answer] do
      p= answer.body
      - if answer.files.attached?
        = render partial: 'attachments/attachment', collection: answer.files
      - if answer.links.any?
        .links-list
          p Links:
          ul
            = render partial: 'links/link', collection: answer.links, locals: { action_cable: action_cable }
    = render 'votes', resource: answer, action_cable: action_cable
    = render 'comments', resource: answer, action_cable: action_cable
    - if action_cable || current_user&.author_of?(@question)
      .best-answer-link class=('hidden' if action_cable)
        p= link_to 'Best answer', answer_best_path(answer), method: :patch, remote: true
    - if action_cable || current_user&.author_of?(answer)
      .change-answer-links class=('hidden' if action_cable)
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
        .edit-answer-form.hidden
          = render partial: 'answers/form', locals: { model: answer, submit_text: 'Save' }

app/views/answers/_form.html.slim
= form_with model: model, remote: true do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  #links
    = f.fields_for :links do |link|
      = render 'link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links
  p= f.submit submit_text

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers.best_first %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.new-answer #answer_body').val('');
  $('.notice').html('<%= notice %>');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();
$('.notice').html('<%= notice %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('#answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>