config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    patch 'users/:id', to: 'registrations#update_email', as: 'user'
  end

  root to: "questions#index"

  concern :votable do
    post :vote, on: :member
  end
  concern :commentable do
    post :comment, on: :member
  end

  resources :questions, only: %i[index show new create update destroy], concerns: [:votable, :commentable] do
    resources :attachments, shallow: true, only: :destroy
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, only: %i[show create update destroy], concerns: [:votable, :commentable] do
      patch :best
    end
  end
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, shallow: true, only: %i[index show create update destroy]
      end
    end
  end

  resource :search, only: :show

  mount ActionCable.server => '/cable'
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true, optional: true

  validates :name, :url, presence: true
  validate :validate_url

  def gist?
    url =~ /^https:\/\/gist\.github\.com/
  end

  private
  
  def validate_url
    errors.add(:url) unless url_valid?(url)
  end

  def url_valid?(url)
    url = URI.parse(url) rescue false
    url.kind_of?(URI::HTTP) || url.kind_of?(URI::HTTPS)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  load_and_authorize_resource

  def destroy
    @link.destroy
  end
end

app/views/links/_form.html.slim
.nested-fields
  p
    = f.label :name, 'Link name'
    = f.text_field :name
  p
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/links/_link.html.slim
- action_cable ||= false
li id="link-#{link.id}"
  - if link.gist?
    = link.name
    script src="#{link.url}.js"
  - else
    = link_to link.name, link.url
  - if action_cable || can?(:destroy, link)
    .delete-link class=('hidden' if action_cable)
      p= link_to 'Delete link', link_path(link), method: :delete, remote: true

app/views/links/destroy.js.erb
$('#link-<%= @link.id %>').remove();
$('.notice').html('<%= notice %>');